### ISSUE TITLE
Feature Request: Allow "Ctrl + Tab" Navigation and Use Last Tab's Title as Group Name

### ISSUE THREAD

**Issue by gustavotrott** [FaisalBinAhmed/tabius#1]
Hello,

Firstly, I'd like to express my appreciation for Tabius. It aligns perfectly with my browsing habits, and I'm genuinely thankful for the effort you've put into developing this extension.

I'd like to propose a feature enhancement that, in my opinion, would improve the user experience:

1. **Navigation within Collapsed Groups with "Ctrl + Tab"**: When the "Auto collapse inactive tab groups" option is activated, it becomes challenging to navigate tabs within a collapsed group using the "Ctrl + Tab" shortcut. My suggestion is to treat the "Group name" as a selectable tab. Once selected (using "Ctrl + Tab"), the group could then expand, automatically focusing on the last active tab within that group.

2. **Use the Last Active Tab's Title as the Group Name**: For better context and continuity, it would be beneficial to set the group name with the title of its last active tab. This way, a user can easily pick up from where they left off.

I believe these changes would elevate the overall experience of using Tabius. I hope you'll consider my suggestions, and I'm eager to hear your thoughts on them.

Thank you for your time and dedication to this project!

**Comment by gustavotrott** [comment]
I'm not sure if the first item is feasible...

Alternatively, it would be good to set a "Minimum idle time" before considering a group as "inactive".
This way I'll be able to navigate using the keyboard between fresh tabs (even grouped) and only old groups will be collapsed.

**Comment by FaisalBinAhmed** [comment]
Hi Gustav @gustavotrott I just noticed this issue. I will get back to you soon.

**Comment by FaisalBinAhmed** [comment]
I just looked into the issue in depth.
FIrstly, thanks for using my extension and raising the issue. I really appreciate it.

1. You are right, the first item is not feasible as this is something only Google can implement. They currently only traverse "open" tabs with ctrl+tab.

2. This would mean to list to every tab change event, find the tab and check if it's in a group, and then change the name of the group. This is quite resource intensive. Maybe if more people ask for it, I might implement it.
3. I like the threshold for considering a group inactive idea. I will explore it if it is feasible. 

Thanks again. @gustavotrott

**Comment by gustavotrott** [comment]
Hey, thanks for your attention @FaisalBinAhmed !

About the item 2, maybe just giving the option to use the Opener "Title", instead of the "domain", would be interesting.

Best regards,
Gustavo

**Comment by FaisalBinAhmed** [comment]
I think using the website title as the group name is absolutely doable. I will put it in the todo list. @gustavotrott
