### ISSUE TITLE
Auto Grouping not working

### ISSUE THREAD

**Issue by wakmail** [FaisalBinAhmed/tabius#3]
Auto Group by domain isn't actively working, I don't know how to fix it.

**Comment by FaisalBinAhmed** [comment]
Hi, thanks for opening an issue. @wakmail 
Could you elaborate more? I personally have it also in auto grouping by domain. 

Could you go to Tabius Settings page, open the console in dev panel and take a screenshot of it expading the settings object. Just post it here, so I can see if you have any conflicting rules. Thanks. :)

<img width="1728" alt="image" src="https://github.com/FaisalBinAhmed/tabius/assets/20614782/1e441ea7-077d-4333-b140-27c0396cbcb5">
