### ISSUE TITLE
Favorites not nested if opened via folder

### ISSUE THREAD

**Issue by Keith94** [FaisalBinAhmed/tabius#7]
Is it possible, in MS Edge, to open favorites in bulk into its own tab group?

![image](https://github.com/FaisalBinAhmed/tabius/assets/5490615/2431e897-3822-46e0-9f98-125fc9b3793b)

**Comment by FaisalBinAhmed** [comment]
This is something the browser should implement. While the extension can check if bunch of tabs are launched at once. The added computation is not worth the use case. :)

**Comment by Keith94** [comment]
Okay I see. Didn't know that. Thanks!
